SOPT-all/35-APPJAM-SERVER-GONGBAEK

src/main/java/com/ggang/be/api/common/ApiResponse.java, src/main/java/com/ggang/be/api/common/PracticeController.java, src/main/java/com/ggang/be/api/common/ResponseBuilder.java, src/main/java/com/ggang/be/api/common/ResponseError.java, src/main/java/com/ggang/be/api/common/ResponseSuccess.java, src/main/java/com/ggang/be/api/exception/GlobalExceptionHandler.java
- #8 
- init/#8
- response body 세팅했어요
- response body 세팅했어요
스크린샷을 첨부해주세요.
closes #8
=> [init] #8 response setting

src/main/java/com/ggang/be/api/common/ResponseError.java, src/main/java/com/ggang/be/api/common/ResponseSuccess.java
- #11 
- init/#11
- ResponseCode 설정
- ResponseSuccess 설정
```java
OK(2000, "성공하였습니다."),
CREATED(2010, "리소스가 성공적으로 생성되었습니다.");
```
- ResponseError 설정
```java
// 400 Bad Request
BAD_REQUEST(4000, "유효하지 않은 요청입니다."),
INVALID_INPUT_VALUE(4001, "검증에 실패하였습니다."),
INVALID_INPUT_IMAGE_VALUE(4002, "지원하지 않는 이미지 확장자입니다."),
INVALID_INPUT_IMAGE_SIZE(4003, "지원하지 않는 이미지 크기입니다."),
INVALID_INPUT_IMAGE_URL(4004, "잘못된 이미지 URL 입니다."),
INVALID_INPUT_LENGTH(4005, "글자수를 초과했습니다."),
// 401 Unauthorized
UNAUTHORIZED_ACCESS(4010, "리소스 접근 권한이 없습니다."),
INVALID_TOKEN(4011, "액세스 토큰의 값이 올바르지 않습니다."),
EXPIRED_TOKEN(4012, "액세스 토큰이 만료되었습니다. 재발급 받아주세요."),
// 404 Not Found
NOT_FOUND(4040, "대상을 찾을 수 없습니다."),
TOKEN_NOT_FOUND(4041, "찾을 수 없는 토큰 타입입니다."),
USER_NOT_FOUND(4042, "유저를 찾을 수 없습니다."),
COMMENT_NOT_FOUND(4043, "해당 댓글을 찾을 수 …
```
=> [init] #11 ResponseCode 설정

build.gradle, src/main/java/com/ggang/be/Application.java, src/main/java/com/ggang/be/api/common/HealthController.java, src/main/java/com/ggang/be/domain/BaseTimeEntity.java, src/main/java/com/ggang/be/domain/advertisement/AdvertisementEntity.java, src/main/java/com/ggang/be/domain/comment/CommentEntity.java, src/main/java/com/ggang/be/domain/constant/Category.java, src/main/java/com/ggang/be/domain/constant/Gender.java, src/main/java/com/ggang/be/domain/constant/Mbti.java, src/main/java/com/ggang/be/domain/constant/Status.java, src/main/java/com/ggang/be/domain/constant/WeekDate.java, src/main/java/com/ggang/be/domain/everyGroup/EveryGroupEntity.java, src/main/java/com/ggang/be/domain/gongbaekTimeTable/GongbaekTimeTableEntity.java, src/main/java/com/ggang/be/domain/lectureTimeTable/LectureTimeTableEntity.java, src/main/java/com/ggang/be/domain/onceGroup/OnceGroupEntity.java, src/main/java/com/ggang/be/domain/school/SchoolEntity.java, src/main/java/com/ggang/be/domain/schoolMajor/SchoolMajorEntity.java, src/main/java/com/ggang/be/domain/user/UserEntity.java, src/main/java/com/ggang/be/domain/userEveryGroup/UserEveryGroupEntity.java, src/main/java/com/ggang/be/domain/userOnceGroup/UserOnceGroupEntity.java
- #10 
- init/#10
- 1차로 구성한 erd에 따라 엔티티를 작성하게 되었고, db관련 의존성을 추가하였습니다.
- 엔티티 추가, mongoDB, spring data jpa, mysql 관련 의존성 추가
스크린샷을 첨부해주세요.
closes #10
=> [init] #10 entity 초기 세팅

src/main/java/com/ggang/be/api/user/controller/UserController.java, src/main/java/com/ggang/be/api/user/dto/UserSchoolResponseDto.java, src/main/java/com/ggang/be/api/user/service/UserService.java, src/main/java/com/ggang/be/domain/user/UserEntity.java, src/main/java/com/ggang/be/domain/user/application/UserServiceImpl.java, src/main/java/com/ggang/be/domain/user/dto/UserDto.java, src/main/java/com/ggang/be/domain/user/dto/UserSchoolDto.java, src/main/java/com/ggang/be/domain/user/infra/UserRepository.java, src/main/java/com/ggang/be/domain/userEveryGroup/UserEveryGroupEntity.java, src/main/java/com/ggang/be/domain/userOnceGroup/UserOnceGroupEntity.java
- #36 
- feat/#36
- 나의 학교명 조회 API 기능 구현
- userId를 통해 School 테이블을 조사해서 학교명을 조회했습니다!
```java
{
"success": true,
"code": 2000,
"message": "성공하였습니다.",
"data": {
"schoolName": "대전가톨릭대학교"
}
}
```
closes #36
=> [feat] 나의 학교명 조회 API 기능 구현

src/main/java/com/ggang/be/api/comment/controller/CommentController.java, src/main/java/com/ggang/be/api/comment/dto/WriteCommentRequest.java, src/main/java/com/ggang/be/api/comment/dto/WriteCommentResponse.java, src/main/java/com/ggang/be/api/comment/service/CommentService.java, src/main/java/com/ggang/be/api/exception/GlobalExceptionHandler.java, src/main/java/com/ggang/be/api/facade/CommentFacade.java, src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java, src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java, src/main/java/com/ggang/be/domain/comment/CommentEntity.java, src/main/java/com/ggang/be/domain/comment/application/CommentServiceImpl.java, src/main/java/com/ggang/be/domain/comment/infra/CommentRepository.java, src/main/java/com/ggang/be/domain/everyGroup/EveryGroupEntity.java, src/main/java/com/ggang/be/domain/everyGroup/application/EveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/onceGroup/OnceGroupEntity.java, src/main/java/com/ggang/be/domain/onceGroup/application/OnceGroupServiceImpl.java, src/main/java/com/ggang/be/domain/user/UserEntity.java, src/main/java/com/ggang/be/global/jwt/JwtService.java, src/test/java/com/ggang/be/domain/comment/CommentFixture.java, src/test/java/com/ggang/be/domain/everyGroup/EveryGroupFixture.java, src/test/java/com/ggang/be/domain/everyGroup/application/EveryGroupServiceImplTest.java, src/test/java/com/ggang/be/domain/onceGroup/OnceGroupFixture.java, src/test/java/com/ggang/be/domain/onceGroup/application/OnceGroupServiceImplTest.java
- #40
- feat/#40
- 댓글 작성 api를 구현합니다.
- 댓글 작성 api를 구현하면서 전에 놓쳤었던 엔티티 코드를 더 개선하였습니다.
- fetchType 설정
- builder, 기본생성자 접근 제어자 지정
- jwt 검증시 Bearer prefix 검사 진행
- 댓글 작성 api 구현
- 테스트 구현하면서 Fixture 활용하는 방식으로 리팩토링 
closes #40
=> [feat] 댓글 작성 api 구현

src/main/java/com/ggang/be/api/facade/GongbaekRequestFacade.java, src/main/java/com/ggang/be/api/facade/GroupFacade.java, src/main/java/com/ggang/be/api/group/controller/GroupController.java, src/main/java/com/ggang/be/api/group/dto/ActiveGroupsResponse.java, src/main/java/com/ggang/be/api/group/dto/GroupRequest.java, src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java, src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java, src/main/java/com/ggang/be/api/lectureTimeSlot/service/LectureTimeSlotService.java, src/main/java/com/ggang/be/api/mapper/GroupResponseMapper.java, src/main/java/com/ggang/be/domain/constant/Status.java, src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupVo.java, src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/application/LectureTimeSlotServiceImpl.java
- #55 
- feat/#55
- 채우기 모임 전체 조회 API 기능 구현
- 채우기 모임 전체 조회 API 기능 구현
- 내 시간표와 겹치는 모임만 조회
- 현재 모집중인 시간표만 조회
- 글 작성시간 기준 역순으로 조회
closes #55
=> [feat] 채우기 모임 전체 조회 API 기능 구현

src/main/java/com/ggang/be/api/common/ResponseError.java, src/main/java/com/ggang/be/api/facade/GroupFacade.java, src/main/java/com/ggang/be/api/group/controller/GroupController.java, src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java, src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java, src/main/java/com/ggang/be/api/userEveryGroup/service/UserEveryGroupService.java, src/main/java/com/ggang/be/api/userOnceGroup/service/UserOnceGroupService.java, src/main/java/com/ggang/be/domain/group/everyGroup/EveryGroupEntity.java, src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/onceGroup/OnceGroupEntity.java, src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java, src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupServiceImpl.java
- #61 
- feat/#61
- 모임 신청 API 기능 구현
- 모임 신청 API 기능 구현
- 이미 신청한 모임은 신청 불가능
- 내가 등록한 모임은 신청 불가능
- 인원이 마감되면 신청 불가능
- 기간이 지나면 신청 불가능
- 신청하면 현재 인원수 1 증가
closes #61
=> [feat] 모임 신청 API 기능 구현

src/main/java/com/ggang/be/api/user/controller/UserController.java
- #65 
- feat/#65
- 나의 학교명 조회 API Token 검증 추가
- 나의 학교명 조회 API Token 검증 추가
closes #65
=> [refactor] 나의 학교명 조회 API Token 검증 추가

Dockerfile
- #67 
- deploy/#67
- 배포 환경 속 yml 적용을 위한 dockerfile 수정
- Dockerfile 수정
스크린샷을 첨부해주세요.
closes #67
=> [deploy] #67 yml 파일 서버와 연계하기 위해 Dockerfile 수정 진행

src/main/java/com/ggang/be/api/facade/GroupFacade.java, src/main/java/com/ggang/be/api/group/controller/GroupController.java, src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java, src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java, src/main/java/com/ggang/be/api/userEveryGroup/service/UserEveryGroupService.java, src/main/java/com/ggang/be/api/userOnceGroup/service/UserOnceGroupService.java, src/main/java/com/ggang/be/domain/group/everyGroup/EveryGroupEntity.java, src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/onceGroup/OnceGroupEntity.java, src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/onceGroup/infra/OnceGroupRepository.java, src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/userEveryGroup/infra/UserEveryGroupRepository.java, src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupServiceImpl.java, src/main/java/com/ggang/be/domain/userOnceGroup/infra/UserOnceGroupRepository.java
- #75 
- feat/#75
- 모임 신청 취소 API 기능 구현
- 모임 신청 취소 API 기능 구현
- 내가 신청하지 않은 모임은 취소 불가능
closes #75
=> [feat] 모임 신청 취소 API 기능 구현

src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/application/LectureTimeSlotServiceImpl.java, src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/infra/LectureTimeSlotRepository.java
- #80 
- fix/#80
- 참여 가능한 모임 조회 조건 수정
```
@Query("SELECT CASE WHEN COUNT(l) > 0 THEN TRUE ELSE FALSE END " +
"FROM lecture_time_slot l " +
"WHERE l.userEntity = :userEntity " +
"AND l.weekDate = :weekDate " +
"AND (" +
"     (l.startTime <= :startTime AND l.endTime > :startTime) " +
"  OR (l.startTime < :endTime AND l.endTime >= :endTime) " +
"  OR (l.startTime > :startTime AND l.endTime < :endTime)" +
")")
boolean isInTime(double startTime, double endTime, UserEntity userEntity, WeekDate weekDate);
```
```
@Override
public boolean isActiveGroupsInLectureTimeSlot(UserEntity findUserEntity, double startTime, double endTime, WeekDate weekDate) {
return !lectureTimeSlotRepository.isInTime(startTime, endTime, findUserEntity, weekDate);
}
```
closes #80
=> [fix] 참여 가능한 모임 조회 조건 수정

src/main/java/com/ggang/be/api/facade/GroupFacade.java, src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java, src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java, src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
- #82 
- fix/#82
- 모임 신청 시 시간표 검증
- 신청할 모임이 나랑 같은 학교인지 검증
```java
@Transactional
public void applyGroup(Long userId, GroupRequest requestDto) {
UserEntity findUserEntity = userService.getUserById(userId);
switch (requestDto.groupType()){
case WEEKLY -> {
EveryGroupEntity everyGroupEntity = everyGroupService.findEveryGroupEntityByGroupId(requestDto.groupId());
sameSchoolValidator.isUserReadMySchoolEveryGroup(findUserEntity, everyGroupEntity);
everyGroupService.validateApplyEveryGroup(findUserEntity, everyGroupEntity);
if(checkGroupsLectureTimeSlot(
findUserEntity,
everyGroupEntity.getGongbaekTimeSlotEntity().getStartTime(),
everyGroupEntity.getGongbaekTimeSlotEntity().getEndTime(),
everyGroupEntity.getGongbaekTimeSlotEntity().getWeekDate())) …
```
=> [fix] 모임 신청 시 시간표 검증 로직 추가

src/main/java/com/ggang/be/api/facade/GroupFacade.java, src/main/java/com/ggang/be/api/group/controller/GroupController.java, src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java, src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java, src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
- #66 
- feat/#66
- 공백채우기 등록하기 API userEveryGroup, userOnceGroup 연계하기!
- 모임 등록을 진행하였을때 해당 작성자도 참가자이므로 연계 테이블에 추가하는 과정을 진행해야한다.
- 추가로 qa 도중 발견하게 된 응답 200 -> 201 로 변경도 함께 진행
스크린샷을 첨부해주세요.
closes #66
=> [feat] 공백채우기 등록하기 API userEveryGroup, userOnceGroup 연계하기!

src/main/java/com/ggang/be/api/user/controller/UserController.java
- #87 
- fix/#87
- 명세서와 다르게 http method 되어있어서 수정 작업 진행합니다.
- get -> post 로 변경
스크린샷을 첨부해주세요.
closes #87
=> [fix] 소개글 검증 api http method get -> post 로 수정

src/main/java/com/ggang/be/api/facade/GroupFacade.java, src/main/java/com/ggang/be/domain/common/SameSchoolValidator.java
- #93 
- fix/#93
- 같은 학교인지 검증하는 로직 추가
- 같은 학교의 모임만 조회할 수 있도록 조건 수정
- 참여 가능한 모임 조회 API
- 채우기 전체 조회 API
closes #93
=> [fix] 같은 학교인지 검증하는 로직 추가

src/main/java/com/ggang/be/api/facade/CommentFacade.java, src/main/java/com/ggang/be/domain/group/vo/GroupCommentVo.java
- #94 
- fix/#94
댓글 작성하기, 조회하기 API qa 검증 후 나타난 오류 수정
- 모임의 참여자가 아닌데 비공개 댓글 작성 불가능하게 변경!
- response body 수정 -> 조회하기 api createdAt 형식 수정!
스크린샷을 첨부해주세요.
closes #94
=> [fix] 댓글 작성하기, 조회하기 API qa 검증 후 나타난 오류 수정

src/main/java/com/ggang/be/api/facade/CommentFacade.java, src/main/java/com/ggang/be/api/facade/GongbaekRequestFacade.java, src/main/java/com/ggang/be/domain/group/IntroductionValidator.java, src/main/java/com/ggang/be/domain/group/LocationValidator.java, src/main/java/com/ggang/be/domain/group/TitleValidator.java, src/main/java/com/ggang/be/domain/group/vo/GroupCommentVo.java, src/main/java/com/ggang/be/global/util/TimeValidator.java, src/test/java/com/ggang/be/global/jwt/JwtServiceTest.java
- #95 
- fix/#95
- qa 과정 중 찾게 된 예외 케이스들에 대한 검증 작업을 실행합니다.
- 여러 케이스 검증 진행하였습니다.
- 모임 제목 검증
- 모임 소개글 검증
- 모임 장소글 검증
- 모임 인원 검증
- 커버 이미지 검증
- due date, weekdate 일치 검증
- 강의 시간 검증 
- 모임 시작, 끝 시간 범위 검증
스크린샷을 첨부해주세요.
내용이 너무 많아! 검증하면서 작성했던 체크리스트를 올립니다..! -> 체크 표시시 검증 완료입니다..!
조금 더 꼼꼼하게 체크하도록 하겠습니다!
closes #95
=> [fix] 공백 등록하기 API qa 진행 중 발생한 버그 수정

src/main/java/com/ggang/be/api/facade/GroupFacade.java, src/main/java/com/ggang/be/api/group/controller/GroupController.java, src/main/java/com/ggang/be/api/group/dto/MyGroupResponse.java
- #98 
- fix/#98
- 나의 모임 조회 API Response Body 수정
- 나의 모임 조회 API Response Body 에서 createdAt 삭제
closes #98
=> [fix] 나의 모임 조회 API Response Body 수정

.github/workflows/gongbaek-build-ci.yml, .github/workflows/gongbaek-cd.yml, .github/workflows/gongbaek-test-ci.yml
- #105 
- deploy/#105
- 배포용 cicd 스크립트를 작성했고 이를 적용시킨다.
- ci/cd workflow 작성
closes #105
=> [deploy] ci/cd 스크립트 작성

.github/workflows/gongbaek-build-ci.yml, .github/workflows/gongbaek-cd.yml, .github/workflows/gongbaek-test-ci.yml, src/main/java/com/ggang/be/api/comment/controller/CommentController.java, src/main/java/com/ggang/be/api/comment/dto/WriteCommentRequest.java, src/main/java/com/ggang/be/api/exception/GlobalExceptionHandler.java, src/main/java/com/ggang/be/domain/comment/CommentEntity.java
- #106 
- feat/#106
- 댓글 검증 요구사항 변경되어서 수정 작업 진행
- 빈 공백만 존재하지 않도록 변경! 글자수는 최대한 늘리는 방향으로
스크린샷을 첨부해주세요.
closes #106
=> [feat] 변경된 댓글 구현 사항 적용해서 진행 

.github/workflows/gongbaek-build-ci.yml, .github/workflows/gongbaek-cd.yml, .github/workflows/gongbaek-test-ci.yml, src/main/java/com/ggang/be/api/comment/controller/CommentController.java, src/main/java/com/ggang/be/api/comment/dto/WriteCommentRequest.java, src/main/java/com/ggang/be/api/exception/GlobalExceptionHandler.java, src/main/java/com/ggang/be/domain/comment/CommentEntity.java, src/main/java/com/ggang/be/domain/group/everyGroup/EveryGroupEntity.java, src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/everyGroup/infra/EveryGroupRepository.java, src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java, src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java
- #101 
- fix/#101
- 모임 신청 취소 API 등록자 권한 수정
- 등록자는 취소하지 못하도록 변경합니다.
- every의 경우 모임 취소를 진행하였을때 delete 쿼리가 날라가지 않은 문제가 있었는데 once의 서비스를 참고하여 해결하였습니다!
전략 패턴
스크린샷을 첨부해주세요.
---
| **BEFORE Diagram**                                                                                     | **AFTER Diagram**                                                                                     |
| :----------------------------------------------------------------------------------------------------: | :---------------------------------------------------------------------------------------------------: |
| ![BEFORE Diagram](https://github.com/user-attachments/assets/38d83340-dede-4d18-b2f5-fe7a45c0fe45)    | ![AFTER Diagram](https://github.com/user-attachments/assets/e8be2523-8312-434e-aa65-3dd3f6534b27) …
=> [fix] 모임 신청 취소 API 등록자 권한 수정

src/main/java/com/ggang/be/api/facade/GroupFacade.java, src/main/java/com/ggang/be/api/group/controller/GroupController.java, src/main/java/com/ggang/be/api/group/dto/ActiveGroupsResponse.java, src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java, src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java, src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/everyGroup/infra/EveryGroupRepository.java, src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/onceGroup/infra/OnceGroupRepository.java
- #116 
- feat/#116
- 카테고리 필터링 조회 기능 추가
- 카테고리 필터링 조회 기능 추가
closes #116
=> [feat] 카테고리 필터링 조회 기능 추가

.github/workflows/gongbaek-build-ci.yml, .github/workflows/gongbaek-cd.yml, .github/workflows/gongbaek-test-ci.yml
- #117 
- deploy/#117
- 배포 도중 발견한 문제 확인하고 deploy 스크립트 실행과정 넣고 보내기
- deploy 실행 스크립트 
closes #117
=> [deploy] 배포도중 발견한 문제 확인하고 deploy 스크립트 넣고 실행해보기

.github/workflows/gongbaek-cd.yml
추가적으로 ls 를 통해 해당 패키지 만들어졌는지 디버깅 용도로 제작하였습니다.
=> [deploy] ls 를 통해 해당 패키지 만들어졌는지 확인

.github/workflows/gongbaek-cd.yml
해당 방식을 통해 앞에 있는 이상한 특수문자 안 넣을 수 있도록 진행
=> [deploy] #117 eof를 통해 secret 값 넣는 방식 시도

src/main/java/com/ggang/be/api/group/dto/ActiveGroupsResponse.java, src/main/java/com/ggang/be/domain/group/dto/GroupVo.java, src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupVo.java, src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupVo.java
- #123 
- fix/#123
- Response Body 에 등록자의 프로필 이미지 추가
- Response Body 에 등록자의 프로필 이미지 추가
closes #123
=> [fix] Response Body 에 등록자의 프로필 이미지 추가

src/main/java/com/ggang/be/domain/userEveryGroup/infra/UserEveryGroupRepository.java
- #124 
- fix/#124
- 잘못 변경된 파라미터 네이밍 수정하여 정상적으로 응답할 수 있도록 수정
- 잘못 매핑된 파라미터를 수정하였습니다.
스크린샷을 첨부해주세요.
| **Weekly 공개하는 경우**                                                                                 | **Once 공개하는 경우**                                                                                   |
| :-----------------------------------------------------------------------------------------------------: | :-----------------------------------------------------------------------------------------------------: |
| ![weekly 공개하는 경우](https://github.com/user-attachments/assets/64ae9988-51a4-41ba-b186-af3f449d2da8) | ![once 공개하는 경우](https://github.com/user-attachments/assets/2a946509-0939-41c8-a128-93a57e16ff04)  |
| **Weekly 모임 참여자가 아닌 경우 false** …
=> [fix] 잘못 변경된 파라미터 네이밍 수정하여 정상적으로 응답할 수 있도록 수정

src/main/java/com/ggang/be/api/group/controller/GroupController.java, src/main/java/com/ggang/be/api/group/everyGroup/strategy/EveryLatestGroupStrategy.java, src/main/java/com/ggang/be/api/group/facade/GroupFacade.java, src/main/java/com/ggang/be/api/group/onceGroup/strategy/OnceLatestGroupStrategy.java, src/main/java/com/ggang/be/api/group/registry/GroupStrategyRegistry.java, src/main/java/com/ggang/be/api/group/registry/LatestGroupStrategy.java, src/main/java/com/ggang/be/api/group/registry/LatestGroupStrategyRegistry.java
- #127 
- refactor/#127
- 참여 가능한 모임 조회 시 ONCE, WEEKLY 분기 클래스 분리
- 참여 가능한 모임 조회 시 ONCE, WEEKLY 분기 클래스 분리
closes #127
=> [refactor] 참여 가능한 모임 조회 시 ONCE, WEEKLY 분기 클래스 분리

src/main/java/com/ggang/be/api/user/controller/UserController.java, src/main/java/com/ggang/be/api/user/dto/UserSchoolResponseDto.java, src/main/java/com/ggang/be/domain/user/application/UserServiceImpl.java, src/main/java/com/ggang/be/domain/user/dto/UserSchoolDto.java, src/main/java/com/ggang/be/domain/user/infra/UserRepository.java
- #129 
- feat/#129
- 홈 화면의 학교명 조회 API 에 response body 에 유저 닉네임 추가
```json
{
"success": true,
"code": 2000,
"message": "성공하였습니다.",
"data": {
"nickname": "아기상어",
"schoolName": "가톨릭대학교"
}
}
```
closes #129
=> [feat] response body 에 유저 닉네임 추가

src/main/java/com/ggang/be/api/group/everyGroup/strategy/ApplyEveryGroupStrategy.java, src/main/java/com/ggang/be/api/group/facade/GroupFacade.java, src/main/java/com/ggang/be/api/group/onceGroup/strategy/ApplyOnceGroupStrategy.java, src/main/java/com/ggang/be/api/group/registry/ApplyGroupStrategy.java, src/main/java/com/ggang/be/api/group/registry/ApplyGroupStrategyRegistry.java
- #133 
- refactor/#133
- 모임 신청 api registry, strategy 기반으로 클래스 분리 진행
- 모임 신청 api registry, strategy 기반으로 클래스 분리 진행
스크린샷을 첨부해주세요.
closes #133
=> [refactor] 모임 신청 API registry, strategy 기반으로 클래스 분리 진행

src/test/java/com/ggang/be/api/school/SearchSchoolFacadeTest.java, src/test/java/com/ggang/be/api/school/SearchSchoolMajorFacadeTest.java
- #157 
- test/#157
- 학교 검색 테스트 코드 작성
- 학과 검색 테스트 코드 작성
- 학교 검색 테스트 코드 작성
- 학과 검색 테스트 코드 작성
closes #157
=> [test] 학교 검색 관련 테스트 코드 작성

src/main/java/com/ggang/be/api/group/controller/GroupController.java, src/main/java/com/ggang/be/api/group/dto/LatestResponse.java, src/main/java/com/ggang/be/api/group/facade/GroupFacade.java, src/main/java/com/ggang/be/domain/group/dto/GroupVo.java, src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupVo.java, src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupVo.java
- #161 
- fix/#161
- 참여 가능한 모임 조회 response body 에 닉네임 추가
- 참여 가능한 모임 조회 response body 에 닉네임 추가
closes #161
=> [fix] 참여 가능한 모임 조회 response body 에 닉네임 추가

src/main/java/com/ggang/be/api/facade/GroupRequestFacade.java, src/main/java/com/ggang/be/api/group/dto/RegisterGongbaekRequest.java, src/main/java/com/ggang/be/domain/group/dto/RegisterGroupServiceRequest.java, src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
- #160 
- fix/#160
- 모임 등록하기 api 수정 진행
- dueDate 필드 삭제
스크린샷을 첨부해주세요.
closes #160
=> [fix] #160 클라이언트 요구에 맞춰 모임 등록하기 API 수정 진행!

src/main/java/com/ggang/be/api/comment/controller/CommentController.java, src/main/java/com/ggang/be/api/group/controller/GroupController.java, src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
- #169 
- fix/#169
- response body -> parameter 로 변경
- response body -> parameter 로 변경
closes #169
=> [fix] GET 메서드 response body -> parameter 로 변경

src/main/java/com/ggang/be/api/group/controller/GroupController.java, src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java, src/main/java/com/ggang/be/api/group/everyGroup/strategy/DeleteEveryGroupStrategy.java, src/main/java/com/ggang/be/api/group/facade/GroupFacade.java, src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java, src/main/java/com/ggang/be/api/group/onceGroup/strategy/DeleteOnceGroupStrategy.java, src/main/java/com/ggang/be/api/group/registry/DeleteGroupStrategy.java, src/main/java/com/ggang/be/api/group/registry/DeleteGroupStrategyRegistry.java, src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java, src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
- #177 
- feat/#177
- 나의 모임 삭제하기 API 기능 구현
- 나의 모임 삭제하기 API 기능 구현
closes #177
=> [feat] 나의 모임 삭제하기 API 기능 구현

src/main/java/com/ggang/be/domain/group/LocationValidator.java
- #181 
- fix/#181
- 기획의 장소 검증 조건 변경에 따라 숫자도 가능하도록 수정하였습니다.
- 장소 검증 조건 변경
- 
스크린샷을 첨부해주세요.
closes #181
=> [fix] #181 장소 검증 조건 변경에 따른 수정 진행

README.md
- #155 
- docs/#155
- read.me 파일 수정
- read.me 파일 수정
closes #155
=> [docs] read.me 파일 수정
